-- Execute no SQL Editor do Supabase antes de implantar o backend.
BEGIN;
CREATE TABLE IF NOT EXISTS public.atividades_usuarios (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    criado_em timestamptz NOT NULL DEFAULT now(),
    usuario_id varchar(64) NOT NULL,
    usuario_nome varchar(150) NOT NULL,
    perfil varchar(50) NOT NULL,
    metodo varchar(10) NOT NULL,
    recurso varchar(255) NOT NULL,
    status integer NOT NULL CHECK (status BETWEEN 100 AND 599)
);
-- IDs podem pertencer a servidores ou cidadãos; não há FK para uma única tabela.
CREATE INDEX IF NOT EXISTS ix_atividades_usuarios_criado_em ON public.atividades_usuarios (criado_em);
CREATE INDEX IF NOT EXISTS ix_atividades_usuarios_usuario_id ON public.atividades_usuarios (usuario_id);
ALTER TABLE public.atividades_usuarios ENABLE ROW LEVEL SECURITY;
-- Leitura autorizada pela API Flask. Sem acesso direto pelo cliente Supabase.
REVOKE ALL ON TABLE public.atividades_usuarios FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.atividades_usuarios_id_seq FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT ON TABLE public.atividades_usuarios TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.atividades_usuarios_id_seq TO service_role;
COMMIT;

-- Verificação pós-migração: RLS ativa e tabela consultável pelo proprietário.
SELECT c.relname, c.relrowsecurity FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = 'public' AND c.relname = 'atividades_usuarios';
SELECT count(*) AS atividades_registradas FROM public.atividades_usuarios;

-- Rollback seguro: primeiro reverta o backend/frontend para a versão anterior.
-- Execute separadamente. Preserva todos os registros para recuperação.
-- BEGIN;
-- ALTER TABLE public.atividades_usuarios RENAME TO atividades_usuarios_arquivo_20261005;
-- COMMIT;
-- Para restaurar, renomeie a tabela arquivada antes de reaplicar a migração.
